// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1bPHf-JELSnZaVveje9PvvPYP68fOouA',
    appId: '1:725343694902:android:c9de896f8529c31ac86897',
    messagingSenderId: '725343694902',
    projectId: 'overcloud-f3f45',
    storageBucket: 'overcloud-f3f45.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTziwzS2IHHHfkRiTG31ngLyi9_TyuME',
    appId: '1:725343694902:ios:c3c46389857f654fc86897',
    messagingSenderId: '725343694902',
    projectId: 'overcloud-f3f45',
    storageBucket: 'overcloud-f3f45.firebasestorage.app',
    iosBundleId: 'com.example.overcloud',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGFyQ93_TUZWc8e2Mu1vnMWYiqM_7UcY',
    appId: '1:725343694902:web:52bec3d85aaea10ac86897',
    messagingSenderId: '725343694902',
    projectId: 'overcloud-f3f45',
    authDomain: 'overcloud-f3f45.firebaseapp.com',
    storageBucket: 'overcloud-f3f45.firebasestorage.app',
    measurementId: 'G-YQ05V9K777',
  );
}
